environment:
  CMD_IN_ENV: "cmd /E:ON /V:ON /C obvci_appveyor_python_build_env.cmd"
  PYTHONIOENCODING: "UTF-8"
  BINSTAR_TOKEN:
    secure: ZHXZzhINhF82bnj8OxVfS5wv8b/98jYE3oqwSKmc5I+1JRmvIV0euxnzCeW8qFkI

  matrix:
    - TARGET_ARCH: "x86"
      CONDA_PY: "27"
      PY_CONDITION: "python >=2.7,<3"
      CONDA_INSTALL_LOCN: "C:\\Miniconda"
    - TARGET_ARCH: "x86"
      CONDA_PY: "34"
      PY_CONDITION: "python >=3.4,<3.5"
      CONDA_INSTALL_LOCN: "C:\\Miniconda3"
    - TARGET_ARCH: "x86"
      CONDA_PY: "35"
      PY_CONDITION: "python >=3.5"
      CONDA_INSTALL_LOCN: "C:\\Miniconda35"
    - TARGET_ARCH: "x64"
      CONDA_PY: "27"
      PY_CONDITION: "python >=2.7,<3"
      CONDA_INSTALL_LOCN: "C:\\Miniconda-x64"
    - TARGET_ARCH: "x64"
      CONDA_PY: "34"
      PY_CONDITION: "python >=3.4,<3.5"
      CONDA_INSTALL_LOCN: "C:\\Miniconda3-x64"
    - TARGET_ARCH: "x64"
      CONDA_PY: "35"
      PY_CONDITION: "python >=3.5"
      CONDA_INSTALL_LOCN: "C:\\Miniconda35-x64"

artifacts:
    - path: 'conda_packages\*.bz2'

platform:
    - x64

install:
    - setlocal enableextensions enabledelayedexpansion
    - cmd: rmdir C:\cygwin /s /q
    - cmd: set CONDA_NPY=19
    - cmd: set "OLDPATH=%PATH%"
    - cmd: set "PATH=%CONDA_INSTALL_LOCN%\\Scripts;%CONDA_INSTALL_LOCN%\\Library\\bin;%PATH%"
    - cmd: conda update --yes --quiet conda
    - cmd: set "PATH=%OLDPATH%"
    - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
    - cmd: conda config --add channels conda-forge
    - cmd: conda config --add channels chemdataextractor
    - cmd: conda config --set show_channel_urls true
    - cmd: conda update --yes --quiet conda
    - cmd: conda install --yes --quiet obvious-ci conda-build-all
    - cmd: set CPU_COUNT=2
    - cmd: set PYTHONUNBUFFERED=1
    - cmd: conda config --set add_pip_as_python_dependency false
    - cmd: conda update -n root --yes --quiet conda
    - cmd: conda install -n root --yes --quiet jinja2 conda-build anaconda-client
    - cmd: conda info
    - cmd: conda config --get

build: false

test_script:
    - '%CMD_IN_ENV% conda-build-all recipes --inspect-channels chemdataextractor --upload-channels chemdataextractor --matrix-conditions "numpy >=1.10" "%PY_CONDITION%"'
    - cmd: mkdir conda_packages
    - cmd: 'copy /Y C:\Miniconda\conda-bld\win-32\*.bz2 conda_packages || cmd /c "exit /b 0"'
    - cmd: 'copy /Y C:\Miniconda-x64\conda-bld\win-64\*.bz2 conda_packages || cmd /c "exit /b 0"'
