{% set name = "ChemDataExtractor" %}
{% set version = "1.2.3" %}
{% set sha256 = "980e995027fc528a4af96621531f3f1d9f9f67f3c27a6d2b950c8c7c20c8d8b3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - appdirs
    - beautifulsoup4
    - click
    - cssselect
    - dawg
    - lxml
    - nltk
    - pdfminer.six
    - python-crfsuite
    - python-dateutil
    - pyyaml
    - requests
    - six

test:
  imports:
    - chemdataextractor
  commads:
    - cde --help

about:
  home: http://chemdataextractor.org
  license: MIT
  license_file: LICENSE
  summary: 'Automatically extract chemical information from scientific documents'
  doc_url: http://chemdataextractor.org/docs
  dev_url: https://github.com/mcs07/ChemDataExtractor

extra:
  recipe-maintainers:
    - mcs07
