{% set name = "python-crfsuite" %}
{% set version = "0.8.4" %}
{% set sha256 = "d54ec1760f9e912abbb42c7fb8d55c2eaabb78d7daa26ee0ae39d010fe8e4426" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - os.h.patch
    - inttypes.h.patch

build:
  number: 0
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]
  script:
    - source activate "${CONDA_DEFAULT_ENV}"  # [unix]
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - toolchain
    - vc   9  # [win and py27]
    - vc  10  # [win and py34]
    - vc  14  # [win and py35]
  run:
    - python

test:
  imports:
    - pycrfsuite

about:
  home: https://github.com/tpeng/python-crfsuite
  license: MIT
  summary: 'Python binding for CRFsuite'

extra:
  recipe-maintainers:
    - mcs07
